import React from 'react';
import { Language } from '../types';
import { TRANSLATIONS } from '../data/translations';
import { 
  ShieldCheck, 
  Award, 
  Database, 
  Cpu, 
  HelpCircle, 
  HeartHandshake, 
  AlertTriangle,
  BookOpen
} from 'lucide-react';

interface AboutViewProps {
  lang: Language;
}

export const AboutView: React.FC<AboutViewProps> = ({ lang }) => {
  const t = TRANSLATIONS[lang];

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      
      {/* Title */}
      <div className="bg-white rounded-xl p-6 border border-stone-200 shadow-sm space-y-2">
        <h2 className="text-xl sm:text-2xl font-bold text-stone-900 tracking-tight">
          {lang === 'te' ? 'స్మార్ట్ పంట సలహాదారు గురించి & శాస్త్రీయ సూత్రాలు' : 'About Smart Crop Advisor & Agronomic Methodology'}
        </h2>
        <p className="text-sm text-stone-600 leading-relaxed">
          {lang === 'te'
            ? 'రైతుల శ్రేయస్సు కోసం అధునాతన నేల మరియు వాతావరణ శాస్త్ర పరిశోధనల ఆధారంగా రూపొందించిన విజ్ఞాన వేదిక.'
            : 'A precision agriculture intelligence engine designed to bridge scientific agronomic research and grassroots smallholder farmers.'}
        </p>
      </div>

      {/* Mandatory Safety & Accuracy Statement */}
      <div className="bg-amber-50/90 border border-amber-300 rounded-2xl p-6 space-y-3 shadow-xs">
        <div className="flex items-center gap-2.5 text-amber-900 font-bold text-base">
          <AlertTriangle className="w-5 h-5 text-amber-700" />
          <span>{lang === 'te' ? 'ముఖ్యమైన శాస్త్రీయ గమనిక & బాధ్యతారాహిత్య ప్రకటన' : 'Scientific Disclaimer & Farmer Guidance Policy'}</span>
        </div>
        <p className="text-xs sm:text-sm text-amber-950 leading-relaxed">
          {lang === 'te'
            ? 'ఈ వెబ్‌సైట్ ద్వారా అందించబడిన దిగుబడి అంచనాలు, రాబడి పరిధులు, ఎరువుల మోతాదులు మరియు పంట సిఫార్సులు పూర్తిగా మార్గదర్శకత్వం కొరకు మాత్రమే. అవి హామీ ఇవ్వబడిన ఫలితాలు కావు. క్షేత్రస్థాయి పరిస్థితులు, విత్తన నాణ్యత, స్థానిక వాతావరణ హెచ్చుతగ్గులు మరియు మార్కెట్ ధరలపై వాస్తవ ఫలితాలు ఆధారపడి ఉంటాయి. పెట్టుబడి పెట్టే ముందు రైతులు తప్పనిసరిగా తమ స్థానిక వ్యవసాయ విస్తరణ అధికారి (AEO) లేదా సమీప కృషి విజ్ఞాన కేంద్రం (KVK) శాస్త్రవేత్తలతో సంప్రదించాలి.'
            : 'Estimated yields, projected revenues, fertilizer quantities, and crop recommendations generated by Smart Crop Advisor are strictly agronomic guidance and do NOT represent guaranteed results. Real agricultural outcomes are governed by unpredictable micro-climates, seed vigor, pest invasions, groundwater fluctuations, and commodity market prices. Farmers are strongly encouraged to verify all recommendations with their local Agricultural Extension Officer (AEO) or Krishi Vigyan Kendra (KVK) prior to final planting investments.'}
        </p>
      </div>

      {/* Recommendation Engine Methodology */}
      <div className="bg-white rounded-xl p-6 border border-stone-200 shadow-sm space-y-4">
        <h3 className="text-base font-bold text-stone-900 flex items-center gap-2">
          <Cpu className="w-5 h-5 text-emerald-600" />
          <span>{lang === 'te' ? 'సిఫార్సుల విశ్లేషణ పద్ధతి (Methodology)' : 'Algorithmic & Machine-Learning Ready Architecture'}</span>
        </h3>
        
        <p className="text-xs sm:text-sm text-stone-700 leading-relaxed">
          {lang === 'te'
            ? 'ఈ వ్యవస్థ ICAR (ఇండియన్ కౌన్సిల్ ఆఫ్ అగ్రికల్చరల్ రీసెర్చ్) మరియు రాష్ట్ర వ్యవసాయ విశ్వవిద్యాలయాల (ANGRAU, PJTSAU) ప్రామాణిక ప్యాకేజ్ ఆఫ్ ప్రాక్టీసెస్ ఆధారంగా 5 కీలక పారామితులను విశ్లేషిస్తుంది:'
            : 'The recommendation engine evaluates a multi-tier agronomic compatibility matrix grounded in published package of practices from the Indian Council of Agricultural Research (ICAR) and State Agricultural Universities:'}
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <div className="p-3 bg-stone-50 rounded-lg border border-stone-200">
            <span className="font-bold text-stone-900 block mb-1">1. Water Deficit Protection</span>
            <p className="text-stone-600">
              Strict non-negotiable logic that penalizes high-water crops (Rice, Sugarcane) when water is rainfed or scarce.
            </p>
          </div>
          <div className="p-3 bg-stone-50 rounded-lg border border-stone-200">
            <span className="font-bold text-stone-900 block mb-1">2. Soil Chemistry & Texture</span>
            <p className="text-stone-600">
              Evaluates soil texture affinity (e.g. Groundnut in light sandy loams vs. Cotton in deep black clays) and pH tolerance curves.
            </p>
          </div>
          <div className="p-3 bg-stone-50 rounded-lg border border-stone-200">
            <span className="font-bold text-stone-900 block mb-1">3. Thermal & Phenological Fit</span>
            <p className="text-stone-600">
              Matches growing temperature bands and monsoonal/seasonal windows (Kharif, Rabi, Summer).
            </p>
          </div>
          <div className="p-3 bg-stone-50 rounded-lg border border-stone-200">
            <span className="font-bold text-stone-900 block mb-1">4. Smallholder Economics</span>
            <p className="text-stone-600">
              Factors in working capital requirements, duration preferences, and risk tolerance of the cultivator.
            </p>
          </div>
        </div>
      </div>

      {/* Datasets & Citations */}
      <div className="bg-white rounded-xl p-6 border border-stone-200 shadow-sm space-y-3">
        <h3 className="text-base font-bold text-stone-900 flex items-center gap-2">
          <Database className="w-5 h-5 text-emerald-600" />
          <span>{lang === 'te' ? 'వినియోగించిన సమాచార వనరులు' : 'Authoritative Datasets & Citations'}</span>
        </h3>
        
        <ul className="text-xs sm:text-sm text-stone-700 space-y-2 list-disc list-inside">
          <li><strong>ICAR-IIRR:</strong> Indian Institute of Rice Research Agronomic Compendium (Hyderabad).</li>
          <li><strong>ICAR-CICR:</strong> Central Institute for Cotton Research Technical Bulletins (Nagpur).</li>
          <li><strong>ICAR-IIPR:</strong> Indian Institute of Pulses Research Pulse Production Guidelines (Kanpur).</li>
          <li><strong>ICAR-IIMR:</strong> Indian Institute of Millets Research Nutri-Cereal Guidelines.</li>
          <li><strong>ANGRAU & PJTSAU:</strong> Vyavasaya Panchangam (Agricultural Almanac & Crop Packages).</li>
          <li><strong>Open-Meteo:</strong> High-resolution micro-climate global meteorological model API.</li>
        </ul>
      </div>

    </div>
  );
};
